### ISSUE TITLE
Not installable on OpenSuse via R console

### ISSUE THREAD

**Issue by limoncelli** [rich-iannone/DiagrammeR#89] opened 2015-03-30 08:30 UTC
HI

I have the following packages installed on opensuse 13.2:

> S | Name                     | Zusammenfassung                          | Typ       
> --+--------------------------+------------------------------------------+-----------
> i | libv8-3                  | JavaScript Engine                        | Paket     
> i | v8                       | JavaScript Engine                        | Paket     
> i | v8-devel                 | Development headers and libraries for v8 | Paket     
> i | v8-private-headers-devel | Private Development headers for v8       | Paket   

but if I run as superuser

> install.packages("DiagrammeR")

I get:

>  8.cpp:221:13: error: ‘class v8::String’ has no member named ‘WriteAscii’
>   mystring->WriteAscii((char*) res.begin());
>             ^
> In file included from V8.cpp:16:0:
> /usr/include/v8.h: In instantiation of ‘static void  
> v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Context]’:
> /usr/include/v8.h:593:17:   required from ‘static void 
> v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, 
> v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Context; M = 0
> v8::NonCopyablePersistentTraits<v8::Context>; T = v8::Context; 
> v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Context>]’
> /usr/include/v8.h:5899:21:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, 
> M>&) [with S = v8::Context; M2 = v8::NonCopyablePersistentTraits<v8::Context>; T = v8::Context; > M = v8::NonCopyablePersistentTraits<v8::Context>]’
> /usr/include/v8.h:658:14:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, 
> M>&) [with T = v8::Context; M = v8::NonCopyablePersistentTraits<v8::Context>]’
> V8.cpp:22:8:   required from here
> /usr/include/v8.h:597:5: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
>      TYPE_CHECK(O, Primitive);
>      ^
> /usr/lib64/R/etc/Makeconf:142: rule for goal  „V8.o“ failed

any idea what I am missing.

best regards

robin

**Comment by pommedeterresautee** [comment] 2015-03-31 08:06
It is not an issue with DiagrammeR but with V8 R package (a dependancy).

In Ubuntu, I have uninstalled V8-devel and reinstalled it.

Hope it helps,
Michaël

**Comment by rich-iannone** [comment] 2015-03-31 08:14
Thanks Michaël for the advice. I agree that it is an issue with V8. Similar issue with a broken build on Mac. A re-install made everything work.

**Comment by pommedeterresautee** [comment] 2015-03-31 18:30
I think this dependency is an issue because it make it a lot harder (5mn instead of 5 seconds) to understand why it doesn t want to install. Is it mandatory to use V8 package?

**Comment by timelyportfolio** [comment] 2015-03-31 18:55
I agree, and the option was my original intent.  Can we `Suggest` rather than `Import` and still be CRAN-worthy?

**Comment by rich-iannone** [comment] 2015-04-12 16:21
Okay, I'm hoping that the non-requirement for V8 during installation means this is no longer an issue. Closing.

**Closed by rich-iannone** 2015-04-12 16:21 UTC

**Comment by jeroenooms** [comment] 2015-04-21 01:16
@limoncelli I would be interested to help you get V8 to work on OpenSUSE. The problem is that the version of `v8-devel` in SuSe is incompatible. But you should be able to get it to work by grabbing V8 version 3.16 from [rubygem](https://rubygems.org/gems/libv8/versions/3.16.14.7) or [rpmfind](http://www.rpmfind.net/linux/rpm2html/search.php?query=v8&system=opensuse). Please open an issue in the v8 repository if you are interested: https://github.com/jeroenooms/v8
