### ISSUE TITLE
exdata files do not match files referenced in README.md

### ISSUE THREAD

**Issue by tclavelle** [rich-iannone/DiagrammeR#228] opened 2017-04-28 18:20 UTC
None of the example diagrams outlined in the repo's README.md file work and it appears that is because the required `.csv` files are missing from the `exdata` directory. 

DiagrammeR version 0.9.0 (installed from CRAN) contains only the following in `exdata`:
```
human_Interactome.sif
karate.gml
neo4j_json_graph
power_grid.graphml
```

The `README.md `, however, contains examples referencing (among others) the following:
```
contributors.csv
projects.csv
projects_and_contributors.csv
```

**Comment by rich-iannone** [comment] 2017-05-10 23:02
Sorry for the confusion caused by this. It was a mistake when building version 0.9.0 for CRAN (`.Rbuildignore` was set to ignore these files, now fixed). For the next release, these files will be available.

I revised `README.md` to include a mention that a file loaded in for the examples is only available in the dev/GitHub version.

**Closed by rich-iannone** 2017-05-10 23:02 UTC
