### ISSUE TITLE
mermaid doesn't generate flowchart

### ISSUE THREAD

**Issue by alexvorobiev** [rich-iannone/DiagrammeR#457] opened 2022-02-19 00:56 UTC
I have tried generating mermaid flowchart (https://mermaid-js.github.io/mermaid/#/flowchart?id=node-shapes):
```r
mermaid("
    flowchart LR
    id1[(Database)]
")
```
and just got the text inside the quotes.

**Comment by lgaborini** [comment] 2022-03-18 11:01
Same here, I have just updated from 1.0.6.1 to 1.0.9 and visNetwork from 2.0.9 to 2.1.0.

**Comment by dinakar29** [comment] 2022-04-26 16:21
I updated the mermaid.js bundle that is installed on the package by running this:

```R
dist_loc <- list.files(
  find.package("DiagrammeR"),
  recursive=T,
  pattern = "mermaid.*js",
  full.names = TRUE
)
js_cdn_url <- "https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.0.1/mermaid.min.js"
download.file(js_cdn_url, dist_loc)
```

Got it to work after that. I believe the existing bundle that ships with the package is outdated.

**Comment by retodomax** [comment] 2023-05-08 08:47
Is there also a way to use the newest version 10.1.0? I replaced line 7 with 

```
js_cdn_url <- 'https://cdn.jsdelivr.net/npm/mermaid@10.1.0/dist/arc-f7872e1e.min.js'
```

but this did not work.

**Comment by olivroy** [comment] 2023-12-04 14:06
Indeed, the bundled mermaid.js is outdated. Duplicate of #475

**Closed by olivroy** 2023-12-04 14:06 UTC
